### PR TITLE
var len double-defined

### PR DESCRIPTION
**Pull request by matteofigus**
This is to fix a bug we found for some specific cookie values. Discussed and manually tested with @jrolfs

### CODE REVIEW

**Review by jrolfs — APPROVED** [review]

**Comment by matteofigus** [comment]
@pennello this PR is to keep the client-side component we use at OpenTable and this source code in sync (as the bundling here is broken due to the fact it uses a broken outdated version of the original forked repo - so this same change was merged into the other repo already 2 months ago).

Any reason this can't be merged?

**Comment by pennello** [comment]
@matteofigus

> Any reason this can't be merged?

No, I don't think so.  But didn't we already review this or something like it last year?  Was it in this repo?  Maybe another one?

**Comment by matteofigus** [comment]
@pennello we reviewed #1 in this repo which fixed something but also broke something 😅 

This basically fixes it 🎉

**Comment by pennello** [comment]
@matteofigus Oh, I see it.  Right on.  Will merge here.

**Review by pennello — APPROVED** [review]

**Pull request merged**
